// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA23eKrEGQn7JN3g4zX8MEoabu8vp16QaA',
    appId: '1:847774021621:web:ccb9d71ba69d5f30b652bc',
    messagingSenderId: '847774021621',
    projectId: 'whochatt-4867e',
    authDomain: 'whochatt-4867e.firebaseapp.com',
    storageBucket: 'whochatt-4867e.appspot.com',
    measurementId: 'G-MNWC47786F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBii3Y49up5HhEChzsHDZDaeVei8cBfAi0',
    appId: '1:847774021621:android:7ee1577217596596b652bc',
    messagingSenderId: '847774021621',
    projectId: 'whochatt-4867e',
    storageBucket: 'whochatt-4867e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqslyK5sBzuf-qr16Rehv2ufOWwdnx8s',
    appId: '1:847774021621:ios:39e4bdaabac3eac8b652bc',
    messagingSenderId: '847774021621',
    projectId: 'whochatt-4867e',
    storageBucket: 'whochatt-4867e.appspot.com',
    iosClientId: '847774021621-j17usee22u2jog0b0tinqsi403si5dlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqslyK5sBzuf-qr16Rehv2ufOWwdnx8s',
    appId: '1:847774021621:ios:39e4bdaabac3eac8b652bc',
    messagingSenderId: '847774021621',
    projectId: 'whochatt-4867e',
    storageBucket: 'whochatt-4867e.appspot.com',
    iosClientId: '847774021621-j17usee22u2jog0b0tinqsi403si5dlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
